### ISSUE TITLE
it had some error with my router,can not enter the app

### ISSUE THREAD

**Issue by CTYick** [OpenWyu/luci-app-esurfing-client#3]
...r/lib/lua/luci/model/cbi/esurfing-client/setting.lua:2: attempt to call method 'get_wandev' (a nil value)
stack traceback:
	...r/lib/lua/luci/model/cbi/esurfing-client/setting.lua:2: in function 'func'
	/usr/lib/lua/luci/cbi.lua:66: in function 'load'
	/usr/lib/lua/luci/dispatcher.lua:1385: in function '_cbi'
	/usr/lib/lua/luci/dispatcher.lua:1056: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:483: in function </usr/lib/lua/luci/dispatcher.lua:482>

**Comment by CTYick** [comment]
your app was instilled into my router (xiaomi nano r1cl) but it did not work in a right status, and this is the error code on my browser

**Comment by LengSword** [comment]
This may be because `luci` can't find the "get_wandev" method.
This problem is usually because your `luci` version doesn't match the project's `luci` version, so you need to modify the code to get the WAN port IP address.

In short, there are two solutions:
1. Modify the code to get the WAN port IP address
2. Update the `luci` version

If you have an older version of luci, perhaps you can refer to my previously modified code, this [commit ](https://github.com/OpenWyu/luci-app-esurfing-client/commit/a4bf026acfe69c7057aac9189724c5ca6928fe38) is for an older version of luci to get the WAN port IP address.
